name: Node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'
    - name: Configure Node and Yarn
      run: |
        echo "Node.js version: $(node --version)"
        npm install -g corepack
        corepack enable
        yarn set version 1.22.22
        yarn config set nodeLinker node-modules
        yarn config set ignore-engines true
    - name: Install Dependencies
      run: |
        yarn install --ignore-engines --network-concurrency 1
    - name: Run Lint
      run: yarn lint
    - name: Run Tests
      run: yarn test
    - name: Run Build
      run: yarn build
