name: Node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'
    - name: Install Dependencies
      run: |
        yarn config set nodeLinker node-modules
        yarn install --network-concurrency 1 --ignore-engines
    - name: Run Lint
      run: yarn lint
    - name: Run Tests
      run: yarn test
    - name: Run Build
      run: yarn build
