name: Node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'
    - name: Configure Node and Yarn
      run: |
        node --version
        npm install -g yarn@1.22.22
        yarn --version
        yarn config set ignore-engines true
        yarn config set network-timeout 300000
    - name: Install Dependencies
      run: |
        export NODE_VERSION=$(node --version)
        echo "Using Node.js version: $NODE_VERSION"
        yarn install --ignore-engines --network-timeout 300000
    - name: Run Lint
      run: yarn lint
    - name: Run Tests
      run: yarn test
    - name: Run Build
      run: yarn build
